---

global:
  application_base_url: ""

registry:
  name: registry # changing this will cause not working config service
  deployment:
    image:
      repository: jhipster/consul-config-loader
      tag: "v0.4.1"
  statefulset:
    image:
      repository: consul
      tag: "1.13.1"
  ingress:
    enable: false
    annotations: {}
    ingressClassName: "nginx"
