apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "rollouts.fullname" . }}
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] > 0.90
    failureConditaion: result[0] < 0.90
    failureLimit: 0
    provider:
      prometheus:
        address: http://monitoring-system-kube-pro-prometheus.monitoring-system:9090
        query: >+
          sum(
            rate(nginx_ingress_controller_requests{ingress={{`"{{ args.ingress }}"`}},status!~"[4-5].*"}[20s]))
            /
            sum(rate(nginx_ingress_controller_requests{ingress={{`"{{ args.ingress }}"`}}[20s])
          )
