{{- if .Values.registry.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.registry.name }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- if .Values.registry.ingress.annotations }}
  annotations:
    {{- $tp := typeOf .Values.registry.ingress.annotations }}
    {{- if eq $tp "string" }}
      {{- tpl .Values.registry.ingress.annotations . | nindent 4 }}
    {{- else }}
      {{- toYaml .Values.registry.ingress.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.registry.ingress.ingressClassName }}
  {{- if .Values.registry.ingress.tls }}
  tls:
    {{- range .Values.registry.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.registry.name }}-{{ .Values.global.application_base_url }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.registry.name }}-service
              port:
                number: 8500
{{- end }}
