{{- if or (not .Values.mariadb.enabled) (not .Values.redis.enabled) (not .Values.elasticsearch.enabled)}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "microblog.fullname" . }}-external"
  labels:
    {{- include "microblog.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.mariadb.enabled }}
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.redis.enabled }}
  redis-password: {{ default "" .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.elasticsearch.enabled }}
  elasticsearch-password: {{ default "" .Values.externalElasticsearch.password | b64enc | quote }}
  {{- end }}
{{- end }}
