{{- if or (not .Values.mariadb.enabled) (not .Values.redis.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "microblog.fullname" . }}-external"
  labels:
    {{- include "microblog.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
  redis-password: {{ default "" .Values.externalRedis.password | b64enc | quote }}
{{- end }}
