{{- if and .Values.main.persistence.enabled .Values.main.persistence.hostPath (not .Values.main.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "microblog.fullname" . }}-microblog
  labels:
    {{- include "microblog.labels" . | nindent 4 }}
  {{- if .Values.main.persistence.annotations }}
  annotations:
  {{ toYaml .Values.main.persistence.annotations | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.main.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.main.persistence.size | quote }}
  hostPath:
    path: {{ .Values.main.persistence.hostPath | quote }}
{{- end -}}
