{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microblog.fullname" . }}
  labels:
    {{- include "microblog.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.smtp.smtpPassword }}
  smtp-password: {{ .Values.smtp.smtpPassword | b64enc | quote }}
  {{- end }}
{{- end }}
