{{- if and .Values.mysql.enabled (not .Values.mysql.auth.existingSecret) }}
{{- if or .Values.mysql.auth.rootPassword .Values.mysql.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "getting-started-app.mysql.fullname" . }}
  labels:
    {{- include "getting-started-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.mysql.auth.rootPassword }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.mysql.auth.password }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}

{{- if not .Values.mysql.enabled }}
{{- if and (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "getting-started-app.fullname" . }}-external-db
  labels:
    {{- include "getting-started-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mysql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
{{- end }}
